version: 0.2

phases:

  install:
    commands:
      - cd db_api
      - ./deploy.sh -i

  build:
    commands:
      - ./deploy.sh -b

artifacts:
  files:
    - "**/*" #Todos los archivos que se generan
  name: BuildArtifact
